
version: 2.1

jobs:
  build:
    # creates a directory in the docker image
    working_directory: ~/just-for-practice 
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run: npm install
      - run: npm run test

    
workflows:
  build_and_test:
    jobs:
      - build
      
