
version: 2.1

jobs:
  build:
    # creates a directory in the docker image
    working_directory: ~/just-for-practice 
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run: index.html

workflows:
    jobs:
      - build
