
version: 2.1

jobs:
  build:
    # creates a directory in the docker image
    working_directory: ~/just-for-practice 
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run: xdg-open ~/just-for-practice/index.html
      
  test:
    working_directory: ~/just-for-practice 
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run: ~/just-for-practice/index.html
    
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
