
version: 2.1

jobs:
  build:
    # creates a directory in the docker image
    working_directory: ~/just-for-practice 
    docker:
      - image: cimg/node:19.9.0
   
    steps:
      - checkout
      - run: npm install

    
workflows:
  building:
    jobs:
      - build
      
