
version: 2.1

jobs:
  build:
    # creates a directory in the docker image
    working_directory: ~/just-for-practice 
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run: npm run index.html
      
  test:
    working_directory: ~/just-for-practice 
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run: open ./index.html
    
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
